x-app: &app
  build: .
  image: imagens-cinza
  environment:
    RABBITMQ_HOST: rabbitmq



services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20


  receivelogs1:
    <<: *app
    command: ["java", "-cp", "app.jar", "org.application.ReceiveLogs", "/output"]
    volumes: ["./servidores/s1:/output:z"]
    depends_on:
      rabbitmq:
        { condition: service_healthy }

  receivelogs2:
    <<: *app
    command: ["java", "-cp", "app.jar", "org.application.ReceiveLogs", "/output"]
    volumes: ["./servidores/s2:/output:z"]
    depends_on:
      rabbitmq:
        { condition: service_healthy }

  worker1:
    <<: *app
    command: ["java", "-cp", "app.jar", "org.application.Worker"]
    depends_on: [receivelogs1, receivelogs2]

  worker2:
    <<: *app
    command: ["java", "-cp", "app.jar", "org.application.Worker"]
    depends_on: [receivelogs1, receivelogs2]

  newtask1:
    <<: *app
    command: [ "java", "-cp", "app.jar", "org.application.NewTask", "/imagens" ]
    volumes: ["./clientes/c1:/imagens:ro,z"]
    depends_on:
      rabbitmq:
        {condition: service_healthy}
    profiles: ["clientes"]

  newtask2:
    <<: *app
    command: [ "java", "-cp", "app.jar", "org.application.NewTask", "/imagens" ]
    volumes: ["./clientes/c2:/imagens:ro,z"]
    depends_on:
      rabbitmq:
        {condition: service_healthy}
    profiles: ["clientes"]